version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: '${APP_NAME}_db'
    volumes:
      - storage:/var/lib/postgresql
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_DATABASE}'

volumes:
  storage:
